package Vistas;

import Conexion.ConexionBD;
import Metodos.Metodos_Mascotas;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class vw_Mascotas extends javax.swing.JFrame {

    private final Metodos_Mascotas CP = new Metodos_Mascotas();
    int num = 0;

    static ResultSet rs = null;
    DefaultTableModel dtm = new DefaultTableModel();

    DefaultTableModel model;

    public vw_Mascotas() {
        initComponents();
        listar();

        this.setLocationRelativeTo(null);
    }

    Metodos_Mascotas metodos = new Metodos_Mascotas();

    private void listar() {
        jtb_Mascotas.setModel(CP.getDatos());
        mirar();
    }

    //LIMPIAR TODOS LOS CAMPOS 
    //*********************************
    private void limpiar() {
        txtId.setText("");
        jcb_tipoAnimal.setSelectedIndex(0);
        jcb_razaAnimal.setSelectedIndex(0);
        txtEdad.setText("");
        jcb_tipoSangre.setSelectedIndex(0);
        txtAlergias.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        

    }

    void mirar() {
        txtId.setEnabled(false);
        jcb_tipoAnimal.setEnabled(false);
        jcb_razaAnimal.setEnabled(false);
        txtEdad.setEnabled(false);
        jcb_tipoSangre.setEnabled(false);
        txtAlergias.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtPrecio.setEnabled(false);

        btnGuardad.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnVolver.setEnabled(true);
    }

    void mascotaMirar() {
        jcb_tipoAnimal.setEnabled(true);
        jcb_razaAnimal.setEnabled(true);
        txtEdad.setEnabled(true);
        jcb_tipoSangre.setEnabled(true);
        txtAlergias.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtPrecio.setEnabled(true);

        btnGuardad.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnVolver.setEnabled(false);
        btnCancelar.setEnabled(true);
    }

    void nuevo() {
        txtId.setEnabled(true);
        jcb_tipoAnimal.setEnabled(true);
        jcb_razaAnimal.setEnabled(true);
        txtEdad.setEnabled(true);
        jcb_tipoSangre.setEnabled(true);
        txtAlergias.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtPrecio.setEnabled(true);

        btnGuardad.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnVolver.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtAlergias = new jtextfieldround.JTextFieldRound();
        txtId = new jtextfieldround.JTextFieldRound();
        jcb_tipoAnimal = new javax.swing.JComboBox<>();
        jcb_razaAnimal = new javax.swing.JComboBox<>();
        txtEdad = new jtextfieldround.JTextFieldRound();
        jcb_tipoSangre = new javax.swing.JComboBox<>();
        txtCantidad = new jtextfieldround.JTextFieldRound();
        txtPrecio = new jtextfieldround.JTextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Mascotas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardad = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtBuscar = new jtextfieldround.JTextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(48, 5));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 55, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mascotas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 50));

        jPanel2.setBackground(new java.awt.Color(251, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Mascotas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(33, 150, 243))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 150, 243));
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 150, 243));
        jLabel3.setText("Tipo Animal:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 150, 243));
        jLabel4.setText("Raza Animal:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 150, 243));
        jLabel6.setText("Edad:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 150, 243));
        jLabel7.setText("Cantidad:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 80, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(33, 150, 243));
        jLabel21.setText("Alergias:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 60, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(33, 150, 243));
        jLabel23.setText("Precio:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 60, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(33, 150, 243));
        jLabel27.setText("Tipo Sangre:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 90, 30));

        txtAlergias.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergias.setForeground(new java.awt.Color(0, 0, 0));
        txtAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergiasActionPerformed(evt);
            }
        });
        txtAlergias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlergiasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlergiasKeyTyped(evt);
            }
        });
        jPanel2.add(txtAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 160, 30));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 90, 30));

        jcb_tipoAnimal.setBackground(new java.awt.Color(204, 204, 204));
        jcb_tipoAnimal.setForeground(new java.awt.Color(0, 0, 0));
        jcb_tipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Perro", "Gato" }));
        jcb_tipoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoAnimalActionPerformed(evt);
            }
        });
        jPanel2.add(jcb_tipoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 30));

        jcb_razaAnimal.setBackground(new java.awt.Color(204, 204, 204));
        jcb_razaAnimal.setForeground(new java.awt.Color(0, 0, 0));
        jcb_razaAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Siberian Husky (Perro)", "Pug (Perro)", "Akita Inu (Perro)", "Azul ruso (Gato)", "Persa (Gato)", "Siamés (Gato)" }));
        jcb_razaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_razaAnimalActionPerformed(evt);
            }
        });
        jPanel2.add(jcb_razaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 140, 30));

        txtEdad.setBackground(new java.awt.Color(204, 204, 204));
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 120, 30));

        jcb_tipoSangre.setBackground(new java.awt.Color(204, 204, 204));
        jcb_tipoSangre.setForeground(new java.awt.Color(0, 0, 0));
        jcb_tipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DEA-1.1 (Perro)", "DEA-1.2 (Perro)", "DEA-3 (Perro)", "DEA 4 (Perro)", "DEA-5 (Perro)", "DEA-6 (Perro)", "DEA-7 (Perro)", "DEA-8 (Perro)", "A (Gato)", "B (Gato)", "AB (Gato)" }));
        jcb_tipoSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoSangreActionPerformed(evt);
            }
        });
        jPanel2.add(jcb_tipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 140, 30));

        txtCantidad.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 160, 30));

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 150, 243));
        jLabel9.setText(" Buscar por Raza y edad:");

        btnMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(0, 0, 102));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/escoba.png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setBorderPainted(false);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMostrar.setFocusPainted(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jtb_Mascotas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtb_Mascotas.setBackground(new java.awt.Color(251, 248, 248));
        jtb_Mascotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtb_Mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtb_Mascotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtb_Mascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_MascotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Mascotas);

        jPanel3.setBackground(new java.awt.Color(0, 55, 133));
        jPanel3.setLayout(null);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regresar.png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolver);
        btnVolver.setBounds(1010, 0, 70, 80);

        jPanel4.setBackground(new java.awt.Color(0, 55, 133));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnGuardad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardad.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar.png"))); // NOI18N
        btnGuardad.setText("Guardar");
        btnGuardad.setBorder(null);
        btnGuardad.setContentAreaFilled(false);
        btnGuardad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardad.setFocusPainted(false);
        btnGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadActionPerformed(evt);
            }
        });
        btnGuardad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnGuardadKeyTyped(evt);
            }
        });
        jPanel4.add(btnGuardad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, -1));

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 760, 42);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(305, 305, 305)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlergiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlergiasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiasKeyPressed

    private void txtAlergiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlergiasKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        boolean retroceso = key == 8;

        if (!(minusculas || mayusculas || espacio || retroceso)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }

        if (txtAlergias.getText().trim().length() == 60) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede tener más de 50 dígitos");
        }
    }//GEN-LAST:event_txtAlergiasKeyTyped

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcb_tipoAnimal.requestFocus();

        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void jcb_tipoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoAnimalActionPerformed

    private void jcb_razaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_razaAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_razaAnimalActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadKeyPressed

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean retroceso = key == 8;

        if (!(numeros || retroceso)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Números");
        }

        if (txtEdad.getText().trim().length() == 2) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede tener más de 2 dígitos");
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void jcb_tipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoSangreActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean retroceso = key == 8;

        if (!(numeros || retroceso)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Números");
        }

        if (txtEdad.getText().trim().length() == 2) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede tener más de 2 dígitos");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean retroceso = key == 8;

        if (!(numeros || retroceso)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Números");
        }

        if (txtEdad.getText().trim().length() == 6) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede tener más de 6 dígitos");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        listar();
        txtBuscar.setText("");
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jtb_MascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_MascotasMouseClicked

        int row = jtb_Mascotas.getSelectedRow();
        txtId.setText(jtb_Mascotas.getValueAt(row, 0).toString());
        jcb_tipoAnimal.setSelectedItem(jtb_Mascotas.getValueAt(row, 1).toString());
        jcb_razaAnimal.setSelectedItem(jtb_Mascotas.getValueAt(row, 2).toString());
        txtEdad.setText(jtb_Mascotas.getValueAt(row, 3).toString());
        jcb_tipoSangre.setSelectedItem(jtb_Mascotas.getValueAt(row, 4).toString());
        txtAlergias.setText(jtb_Mascotas.getValueAt(row, 5).toString());
        txtCantidad.setText(jtb_Mascotas.getValueAt(row, 6).toString());
        txtPrecio.setText(jtb_Mascotas.getValueAt(row, 7).toString());
        num = 1;
        mascotaMirar();
    }//GEN-LAST:event_jtb_MascotasMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        vw_Principal ventana = new vw_Principal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
        limpiar();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadActionPerformed
//VALIDAR CAMPOS PARA QUE TODOS ESTEN LLENOS
        //--------------------------------------------------
        if (jcb_tipoAnimal.getSelectedItem().toString().isEmpty() || jcb_razaAnimal.getSelectedItem().toString().isEmpty() || txtEdad.getText().isEmpty()
                || jcb_tipoSangre.getSelectedItem().toString().isEmpty() || txtAlergias.getText().isEmpty() || txtCantidad.getText().isEmpty() || txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            //--------------------------------------------------
        } else {

            String Id = txtId.getText();
            String tipoAnimal = jcb_tipoAnimal.getSelectedItem().toString();
            String razaAnimal = jcb_razaAnimal.getSelectedItem().toString();
            int edad = Integer.parseInt(txtEdad.getText());
            String tipoSangre = jcb_tipoSangre.getSelectedItem().toString();
            String alergias = txtAlergias.getText();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            Double precio = Double.parseDouble(txtPrecio.getText());

            if (num == 0) {
                int respuesta = metodos.guardarMascotas(tipoAnimal, razaAnimal, edad, tipoSangre, alergias, cantidad, precio);
                if (respuesta > 0) {
                    listar();

                    limpiar();
                }
            }
            if (num != 0) {
                int respuesta = metodos.actualizarMascotas(Id, tipoAnimal, razaAnimal, edad, tipoSangre, alergias, cantidad, precio);
                if (respuesta > 0) {
                    listar();
                    num = 0;
                }
            }
        }
    }//GEN-LAST:event_btnGuardadActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jtb_Mascotas.getSelectedRowCount();
        if (fila < 1) {
            JOptionPane.showMessageDialog(null, "Seleccione Un registro de la tabla");
        } else if (fila == 1) {
            int result = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el registro?", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                if (CP.eliminarMascotas(jtb_Mascotas.getValueAt(jtb_Mascotas.getSelectedRow(), 0).toString()) > 0) {
                    limpiar();
                    listar();
                }
            }
            if (result == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!");

            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        mirar();
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        cargar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiasActionPerformed

    private void btnGuardadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardadKeyTyped

    private void btnGuardadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardadKeyPressed
//VALIDAR CAMPOS PARA QUE TODOS ESTEN LLENOS
        //--------------------------------------------------
        if (jcb_tipoAnimal.getSelectedItem().toString().isEmpty() || jcb_razaAnimal.getSelectedItem().toString().isEmpty() || txtEdad.getText().isEmpty()
                || jcb_tipoSangre.getSelectedItem().toString().isEmpty() || txtAlergias.getText().isEmpty() || txtCantidad.getText().isEmpty() || txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            //--------------------------------------------------
        } else {

            String Id = txtId.getText();
            String tipoAnimal = jcb_tipoAnimal.getSelectedItem().toString();
            String razaAnimal = jcb_razaAnimal.getSelectedItem().toString();
            int edad = Integer.parseInt(txtEdad.getText());
            String tipoSangre = jcb_tipoSangre.getSelectedItem().toString();
            String alergias = txtAlergias.getText();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            Double precio = Double.parseDouble(txtPrecio.getText());

            if (num == 0) {
                int respuesta = metodos.guardarMascotas(tipoAnimal, razaAnimal, edad, tipoSangre, alergias, cantidad, precio);
                if (respuesta > 0) {
                    listar();

                    limpiar();
                }
            }
            if (num != 0) {
                int respuesta = metodos.actualizarMascotas(Id, tipoAnimal, razaAnimal, edad, tipoSangre, alergias, cantidad, precio);
                if (respuesta > 0) {
                    listar();
                    num = 0;
                }
            }
        }
    }//GEN-LAST:event_btnGuardadKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vw_Mascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vw_Mascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vw_Mascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vw_Mascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vw_Mascotas().setVisible(true);
            }
        });
    }

    void cargar(String valor) {
        String mostrar = "SELECT * FROM mascota" + " where razaAnimal || edad like '%" + valor + "%'";
        String[] titulos = {"idMascota", "tipoAnimal", "razaAnimal", "edad", "tipoSangre", "alergias", "cantidad", "precio"};
        String[] Registros = new String[8];
        model = new DefaultTableModel(null, titulos);

        try {
            Statement st = cn.createStatement();
            ResultSet rr = st.executeQuery(mostrar);
            while (rr.next()) {
                Registros[0] = rr.getString("idMascota");
                Registros[1] = rr.getString("tipoAnimal");
                Registros[2] = rr.getString("razaAnimal");
                Registros[3] = rr.getString("edad");
                Registros[4] = rr.getString("tipoSangre");
                Registros[5] = rr.getString("alergias");
                Registros[6] = rr.getString("cantidad");
                Registros[7] = rr.getString("precio");
                model.addRow(Registros);
            }
            jtb_Mascotas.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    ConexionBD cc = new ConexionBD();
    Connection cn = cc.conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardad;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_razaAnimal;
    private javax.swing.JComboBox<String> jcb_tipoAnimal;
    private javax.swing.JComboBox<String> jcb_tipoSangre;
    private javax.swing.JTable jtb_Mascotas;
    private jtextfieldround.JTextFieldRound txtAlergias;
    private jtextfieldround.JTextFieldRound txtBuscar;
    private jtextfieldround.JTextFieldRound txtCantidad;
    private jtextfieldround.JTextFieldRound txtEdad;
    private jtextfieldround.JTextFieldRound txtId;
    private jtextfieldround.JTextFieldRound txtPrecio;
    // End of variables declaration//GEN-END:variables
}
